{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "certificate-tools.fullname" . }}
  labels:
    {{- include "certificate-tools.labels" . | nindent 4 }}
type: Opaque
data:
  AZURE_CLIENT_SECRET: {{ .Values.secrets.azureClientSecret | b64enc | quote }}
  FLASK_SECRET_KEY: {{ .Values.secrets.flaskSecretKey | default (randAlphaNum 32) | b64enc | quote }}
{{- end }}
